# Teoretični izpit tečaja Analitika podatkov v Python-u

Čas reševanja: `90 min`

Skupno število točk: `30 pts`

Odgovore na vprašanja vnesite v celice s komentarjem `# Odgovor`

Za vsa vprašanja smo na voljo.

Lahko si pomagate z uporabo gradiv in internetom. Ne pozabite na uradno dokumentacijo.

Srečno!!

**Pred začetkom izpita zaženite spodnjo celico:**

In [2]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

import requests
from bs4 import BeautifulSoup

### 1.del - Numpy

`Možne točke: 5 pts`

##### 1.1) Ustvarite Numpy array `1 pts`

Ustavrite Numpy array z vrednostmi od 1 do vključno 50.

In [3]:
# Odgovor

np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

Želena rešitev:
    
```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])
```

##### 1.2) Negirajte vse elemente Numpy array-a, ki so med med 3 in vključno 8. `1 pts`

In [40]:
Z = np.arange(11)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# Odgovor

Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

Želena rešitev:
```
array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])
```

##### 1.3) Ustvarite in sortirajte naključni array. `2 pts`



Ustvarite Numpy array 10 naključnih števil in ga sortirajte od najmanjšega do največjega števila.

In [98]:
np.random.seed(2)

# Odgovor
Z = np.random.random(10)
Z.sort()
print(Z)

[0.02592623 0.20464863 0.26682728 0.29965467 0.33033482 0.4203678
 0.43532239 0.4359949  0.54966248 0.61927097]


Želena rešitev:
    
```
array([0.02592623, 0.20464863, 0.26682728, 0.29965467, 0.33033482,
       0.4203678 , 0.43532239, 0.4359949 , 0.54966248, 0.61927097])
```

##### 1.4) Pretvorite 32-bitni float Numpy array v 64-bitni integer Numpy array. `1 pts`

In [99]:
Z = np.arange(10, dtype=np.float32)
Z.dtype

dtype('float32')

In [102]:
# Odgovor
Z = np.arange(10, dtype=np.int64)
Z.dtype


dtype('int64')

Za pravilni odgovor mora spodnja celica vrniti naslednje:
```
dtype('int64')
```

### 2. del - pandas 1/3

`Možne točke: 5 pts`

##### 2.1) Kako naredimo pandas Series iz sledečih podatkovnih tipov? `1 pts`

Izdelajte pandas Series iz vsakega spodnjega podatkovnega tipa: list, numpy array, dictionary.

In [103]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [108]:
# Odgovor 1 - mylist
ser1 = pd.Series(mydict)

# Odgovor 2 - myarr
ser2 = pd.Series(myarr)

# Odgovor 3 - mydict
ser3 = pd.Series(mydict)

Za pravilni odgovor mora spodnja celica vrniti `pandas.core.series.Series` za vsako spremenljivko.

In [107]:
print(type(ser1))
print(type(ser2))
print(type(ser3))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


##### 2.2) Kako združimo dve pandas Series v pandas Dataframe  `1 pts`

Združi series1 in series2 v dataframe.

In [119]:
series1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
series2= pd.Series(np.arange(26))

In [120]:
# Odgovor
df = pd.DataFrame({'col1': series1, 'col2': series2})
print(df.head())

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


Za pravilni odgovor mora spodnja celica vrniti dataframe naslednje oblike:

```
  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4
```

##### 2.3) Kako izračunamo število zankov vsake besede v  pandas Series?  `2 pts`

Izračunajte število znakov v vsaki besedi v `ser_beseda`. Naredite nov pandas dataframe, ki vsebuje dva stolpca: besede (ser_beseda) in stevilo_znakov (izračunano stevilo znakov).

In [121]:
ser_beseda = pd.Series(['veliko', 'zannje', 'kako', 'ne', 'pandasinnumpy'])

In [131]:
# Odgovor


df_stevilo = pd.DataFrame({'besede':ser_beseda, 'stevilo_znakov':ser_beseda.map(lambda x: len(x))})
print(df_stevilo)

          besede  stevilo_znakov
0         veliko               6
1         zannje               6
2           kako               4
3             ne               2
4  pandasinnumpy              13


Za pravilni odgovor mora spodnja celica vrniti dataframe naslednje oblike:
    
```
          besede  stevilo_znakov
0         veliko               6
1         zannje               6
2           kako               4
3             ne               2
4  pandasinnumpy              13
```

##### 2.4) Kako pretvorimo pandas series s stringi datumov v pandas timeseries?  `1 pts`

Dani pandas series `ser_times` pretvorite v pandas timeseries tipa datetime64[ns].

In [132]:
ser_times = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [135]:
# Odgovor

set_datatime = pd.to_datetime(ser_times)
print(set_datatime)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


Za pravilni odgovor mora spodnja celica vrniti series naslednje oblike:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

### 3. del - pandas 2/3

`Možne točke: 5 pts`

##### 3.1) Kako izpišemo zadnje 3 vrstice pandas dataframe-a, kjer je vsota vrstic večja od 100?  `2 pts`

Izpišite zadnje 3 vrstice dataframe-a katerega vsota vrstic je večja od 100.

In [142]:
np.random.seed(1)
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)

     0   1   2   3
0   15  21  22  18
1   19  21  15  25
2   10  26  11  22
3   17  23  38  16
4   35  28  30  15
5   28  30  21  38
6   20  38  39  24
7   28  14  33  33
8   19  27  33  10
9   32  23  19  19
10  17  39  32  35
11  11  10  38  27
12  18  34  23  29
13  25  20  35  18
14  17  13  16  31


In [150]:
# Odgovor
rowsums = df.apply(np.sum, axis=1)
df_last_3 = df.iloc[np.where(rowsums > 100)[0][-3:], :]

Za pravilni odgovor mora spodnja celica vrniti dataframe naslednje oblike:
```
     0   1   2   3
7   28  14  33  33
10  17  39  32  35
12  18  34  23  29
```

In [149]:
print(df_last_3)

     0   1   2   3
7   28  14  33  33
10  17  39  32  35
12  18  34  23  29


##### 3.2) Kako dodamo dva stolpca pandas dataframe-u, ki vsebujeta max in min vrednost vsake vrstice? `2 pts`

Danemu pandas dataframe-u dodajte dva stolpca, ki vsebujeta max in min vrednost vsake vrstice.

In [179]:
np.random.seed(2)
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [159]:
df

0   1   2   3   4   5   6   7   8   9
0  41  16  73  23  44  83  76   8  35  50
1  96  76  86  48  64  32  91  21  38  40
2  68   5  43  52  39  34  59  68  70  89
3  69  47  71  96  84  32  67  81  53  77
4  51   5  91  64  80  50  40  47   9  51
5  16   9  18  23  74  58  91  63  84  97
6  44  33  27   9  77  11  41  35  61  10
7  71  87  71  20  57  83   2  69  41  82

In [188]:
# Odgovor

min_df = np.min(df, axis=1)
max_df = np.max(df, axis=1)

df = df.assign(min = (min_df),  max = (max_df))

Za pravilni odgovor mora spodnja celica vrniti dataframe naslednje oblike:
```
    0   1   2   3   4   5   6   7   8   9  min  max
0  41  16  73  23  44  83  76   8  35  50    8   83
1  96  76  86  48  64  32  91  21  38  40   21   96
2  68   5  43  52  39  34  59  68  70  89    5   89
3  69  47  71  96  84  32  67  81  53  77   32   96
4  51   5  91  64  80  50  40  47   9  51    5   91
5  16   9  18  23  74  58  91  63  84  97    9   97
6  44  33  27   9  77  11  41  35  61  10    9   77
7  71  87  71  20  57  83   2  69  41  82    2   87
```

In [189]:
print(df)

    0   1   2   3   4   5   6   7   8   9  min  max
0  41  16  73  23  44  83  76   8  35  50    8   83
1  96  76  86  48  64  32  91  21  38  40   21   96
2  68   5  43  52  39  34  59  68  70  89    5   89
3  69  47  71  96  84  32  67  81  53  77   32   96
4  51   5  91  64  80  50  40  47   9  51    5   91
5  16   9  18  23  74  58  91  63  84  97    9   97
6  44  33  27   9  77  11  41  35  61  10    9   77
7  71  87  71  20  57  83   2  69  41  82    2   87


##### 3.3)  Izbira vrstic in stolpcev `1 pts`

Iz spodnjih podatkov sestavite dataframe z imenom `exam_df`. List `labels` naj bodo index-i dataframe-a.

Iz sestavljenega dataframe-a izberite stolpca `'name' in 'score'` ter vrstice `c, d in e`.

Podatki:

In [190]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [193]:
# Odgovor

exam_df = pd.DataFrame(exam_data, labels)

exam_df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Želena rešitev:
```
        name  score
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
```

### 4.del - pandas 3/3

`Možne točke: 5 pts`

Dataframe `df_grade` za naslednji sklop nalog:

In [28]:
df_grade = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}, 
index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

In [29]:
df_grade

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

##### 4.1)  Izbira podatkov glede na dani kriteriji `1 pts`

Iz dataframe-a `df_grade` izberite vrstice, ki izpolnjujejo naslednja pogoja:
- vrednost stolpca 'attempts' je **manjša ali enaka**  2,
- vrednost stolpca 'score' je **večja** od 12.

In [31]:
# Odgovor





Želena rešitev:
```
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
c  Katherine   16.5         2     yes
g    Matthew   14.5         1     yes
j      Jonas   19.0         1     yes
```

##### 4.2)  Sprememba vrednosti v dataframe-u `1 pts`

V `df_grade`spremenite vrednost vrstice `d` in stolpca `score` v 11.5.

In [35]:
# Odgovor




Želena rešitev:
```
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
```

##### 4.3) Izračun vsote `1 pts`

Izračunajte vsoto stolpca `attempts` v `df_grade`.

In [37]:
# Odgovor




Želen odgovor:

```
Vsota je 19
```

##### 4.4) Razvrščanje podatkov `2pts`

Dataframe `df_grade` razvrstite glede na podatke v stolpcu `name`:
- v padajočem vrstnem redu
- v naraščajočem vrstnem redu


In [ ]:
# Odgovor



Želena rešitev:
    
```
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James   11.5         3      no
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
i      Kevin    8.0         2      no
h      Laura    NaN         1      no
g    Matthew   14.5         1     yes
f    Michael   20.0         3     yes

in

        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes
```

### 5.del - matplotlib

`Možne točke: 5 pts`

Podatki za naloge:

In [42]:
x1 = [1,2,3,4,5,6,7,8,9,10]
y1 = [3,5,6,4,5,8,7,5,8,9]
y2 = [12,16,17,15,14,18,20,16,13,11]

##### 5.1) Naloga 1  `1 pts`

Izrišite nepovezane točke (x1, y1). Točke naj bodo **rdeče** barve.

Graf naj bo poimenovan **Naloga 1**.

Os x naj bo poimenovana **os x**.

Os y naj bo poimenovana **os y**.

In [ ]:
# Odgovor




Želena rešitev:

<img width=300 src="./data/slika2.png">

##### 5.2) Naloga 2  `1 pts`

Ustvarite 2 grafa v isti figuri:
- Na prvega zrišite graf povezanih točk (x1, y1). Graf naj bo **zelene barve**.
- Na drugega izrišite graf povezanih točk (x1, y2). Graf naj bo **črne barve**.

In [45]:
# Odgovor





Želena rešitev:

<img width=300 src="./data/slika5.png">

##### 5.3) Naloga 3  `1 pts`

V isti graf izrišite povezane točke (x1, y1) in (x1, y2).

Omejite y os na interval **od minimalne** vrednosti izmed podatkov y1 in y2, **do maksimalne** vrednosti izmed podatkov y1 in y2.

In [47]:
# Odgovor





Želena rešitev:

<img width=300 src="./data/slika3.png">

##### 5.4) Naloga 4  `1 pts`

V isti graf izrišite povezane točke (x1, y1) in (x1, y2).

Prvi nabor točk poimenujte **Podatki 1**, drugi nabor točk poimenujte **Podatki 2**.

Na grafu prikažite legendo.

In [49]:
# Odgovor






Želena rešitev:

<img width=300 src="./data/slika4.png">

##### 5.5) Naloga 5  `1 pts`

V isti graf izrišite povezane točke (x1, y1) in (x1, y2).

Nastavite, da graf izriše **pomožne črte** (grid).

Na x osi nastavite **ticks** na **vsako drugo vrednost iz x1 seznama**.

In [52]:
# Odgovor





Želena rešitev:

<img width=300 src="./data/slika1.png">

### 6.del - Webscraping 

`Možne točke: 5 pts`

Podatki za naloge:

In [4]:
link = "https://en.wikipedia.org/w/index.php?title=Chernobyl_(miniseries)&direction=next&oldid=899952822"

##### 6.1) HTTP GET  request `1 pts`

Naredite http zahtevek na zgornjo spletno stran (spremenljivka `link`). Izpišite kodo uspešnosti zahtevka, ki vam jo vrne strežnik in html kodo strani.

In [6]:
# Odgovor




Želena rešitev:

```
200

<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">
<head>
<meta charset="UTF-8"/>
<title>Chernobyl (miniseries) - Wikipedia</title>
<script>document.documentElement.className=document.documentElement.className.replace(/(^|\s)client-nojs(\s|$)/,"$1client-js$2");RLCONF={"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":!1,"wgNamespaceNumber":0,"wgPageName":"Chernobyl_(miniseries)","wgTitle":"Chernobyl (miniseries)","wgCurRevisionId":899952822,"wgRevisionId":899952822,"wgArticleId":55876266,"wgIsArticle":!0,"wgIsRedirect":!1,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 Lithuanian-language sources (lt)",
...
```

##### 6.2) Izpis naslovov `2 pts`

Izpišite naslove prvih štirih epizod.

In [11]:
# Odgovor





Za pravilno rešitev mora celica vrniti:
```
"1:23:45"
"Please Remain Calm"
"Open Wide, O Earth"
"The Happiness of All Mankind"
```

##### 6.3) Imena igralcev `2 pts`

Želimo izvedeti ime in priimek prvih treh igralcev napisanih na wikipedia povezavi (več na spodnji sliki, zanimajo nas igralci v rdečem okvirčku).

Dodatno želimo za vsakega izvedeti njegov datum rojstva (datum rojstva najdemo na strani igralca).

<img width=300 src="data/chenobyl.PNG">

In [17]:
# Odgovor





Za pravilno rešitev mora celica vrniti:
```
Jared Harris, rojen 1961-08-24
Stellan Skarsgård, rojen 1951-06-13
Paul Ritter, rojen 1966-03-05
```

## Oddaja

Rešeni notebook pošljite na naslednja e-mail naslova:
- leon.stefanic@ltfe.org 
- gregor.balkovec@ltfe.org

**POMEMBNO!** Pred pošiljanjem notebook preimenujte na naslednji način:

`IZPIT_TEORIJA_IME_PRIMEK`