In [47]:
import numpy as np

# **1.**

In [48]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# **2.**

In [18]:
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# **3.**

In [32]:
y = np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# **4.**

In [34]:
print(y[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# **5.**

In [52]:
x1 = np.arange(9).reshape((3, 3))
print(x1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


# **6.**

In [118]:
a = np.array([1,2,0,0,4,0])

np.nonzero(a), a.dtype


((array([0, 1, 4]),), dtype('int64'))

# **7.**

In [96]:
x2 = np.identity(3)
print(x2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **8.**

In [105]:
np.random.random((3,3,3))

array([[[0.27479275, 0.57592555, 0.54052797],
        [0.89961318, 0.01487141, 0.74103738],
        [0.78820597, 0.83869184, 0.07696559]],

       [[0.83486349, 0.46826591, 0.39089917],
        [0.47597209, 0.26505312, 0.20683335],
        [0.35219355, 0.26548778, 0.06121367]],

       [[0.01130197, 0.59896732, 0.27089119],
        [0.78689388, 0.45033676, 0.78019274],
        [0.14228767, 0.31080652, 0.3103282 ]]])

# **9.**

In [111]:
a1 = np.random.random((10,10))
Zmin = np.min(a1)
Zmax = np.max(a1)
print(Zmin, Zmax)


0.01032869502575462 0.9531352955749159


# **10.**

In [127]:
x3 = np.ones((10,10))
print(x3)
print()
x3[1:-1,1:-1] = 0
print(x3)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# **11.**

In [128]:
0 * np.nan

nan

In [165]:
np.nan == np.nan

False

In [130]:
np.inf > np.nan

False

In [131]:
np.nan - np.nan

nan

In [133]:
0.3 == 3 * 0.1

False

# **12.**

In [151]:
x4 = np.zeros((8,8), dtype = 'int')
print(x4)
print()
x4[1::2, ::2] = 1
x4[::2, 1::2] = 1
print(x4)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# **13.**

In [164]:
Z = np.arange(11)
Z[(Z > 3) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


# **14.**

In [173]:
Z = np.linspace(0,1,11, endpoint = False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# **15.**

In [176]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.0683517  0.28408281 0.307318   0.35236134 0.35301207 0.45149429
 0.47403574 0.66178625 0.66913257 0.80932656]


# **16.**

In [179]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
eq = np.allclose(A,B)
eq1 = np.array_equal(A,B)
print(eq, eq1)

False False


# **17.**

In [187]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


ValueError: assignment destination is read-only

# **18.**

In [197]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.6616877  0.25788106 0.68285416 0.39466135 0.42487256 0.70323524
 0.         0.69133027 0.75119021 0.81869683]


# **19.**

In [201]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v).argmin())
print(Z[index])

67


# **20.**

In [213]:
Z = np.arange(10, dtype = np.int32)
Z = Z.astype(np.float32)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# **21.**

In [221]:
Z = np.random.randint(0,10,50)
print(Z)
print()
print(np.bincount(Z))
print()
print(np.bincount(Z).argmax())

[9 3 5 1 2 6 1 6 1 6 6 1 7 5 6 3 0 0 4 1 4 2 9 6 0 9 5 2 3 0 7 6 8 2 2 3 2
 7 3 9 5 5 1 3 6 7 4 5 6 3]

[4 6 6 7 3 6 9 4 1 4]

6
